FileIDList:
fileid_collisionsprite_bank             equ 0
fileid_collisionsprite_map              equ 1
fileid_collisionsprite_palette          equ 2
fileid_collisiontiles_bank              equ 3
fileid_collisiontiles_map               equ 4
fileid_collisiontiles_palette           equ 5
fileid_herotest_sprite_bank             equ 6
fileid_herotest_palette                 equ 7
fileid_herotest_sprite                  equ 8
fileid_herotest_big_sprite_bank         equ 9
fileid_herotest_big_palette             equ 10
fileid_herotest_big_sprite              equ 11
fileid_testsprite_sprite_bank           equ 12
fileid_testsprite_palette               equ 13
fileid_testsprite_sprite                equ 14
fileid_testsprite2_sprite_bank          equ 15
fileid_testsprite2_palette              equ 16
fileid_testsprite2_sprite               equ 17
fileid_testtiles_bank                   equ 18
fileid_testtiles_map                    equ 19
fileid_testtiles_palette                equ 20
fileid_untitled_splash_bank             equ 21
fileid_untitled_splash_map              equ 22
fileid_untitled_splash_palette          equ 23
fileid_herotestpng_sprite_bank          equ 24
fileid_herotestpng_palette              equ 25
fileid_herotestpng_sprite               equ 26
fileid_housetiles_bank                  equ 27
fileid_housetiles_map                   equ 28
fileid_housetiles_palette               equ 29
fileid_signpost_sprite_bank             equ 30
fileid_signpost_palette                 equ 31
fileid_signpost_sprite                  equ 32
fileid_stoneblock_sprite_bank           equ 33
fileid_stoneblock_palette               equ 34
fileid_stoneblock_sprite                equ 35
fileid_testmap_map                      equ 36
fileid_testmap_collisionmap             equ 37
fileid_testmap2_map                     equ 38
fileid_testmap2_collisionmap            equ 39
fileid_overworld_goc                    equ 40
fileid_dungeon_01_rc                    equ 41
fileid_overworld_rc                     equ 42
